source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '4.2.4'
gem 'pg'
gem 'ace-rails-ap'
gem 'acts-as-taggable-on'
gem 'autoprefixer-rails'
gem 'bootstrap_form'
gem 'bootstrap_tokenfield_rails'
gem 'bunny'
gem 'cancan'
gem 'coffee-rails'
gem 'daemons'
gem 'default_value_for'
gem 'devise'
gem 'diffy'
gem 'exception_notification'
gem 'figaro'
gem 'haml-rails'
gem 'highline'
gem 'honeypot-captcha'
gem 'htmlentities'
gem 'httparty'
gem 'jbuilder'
gem 'jquery-fileupload-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-turbolinks'
gem 'kaminari'
gem 'less-rails'
gem 'less-rails-bootstrap'
gem 'nokogiri'
gem 'paper_trail'
gem 'paperclip'
gem 'rails_autolink'
gem 'rails_script'
gem 'ransack'
gem 'sanitize'
gem 'seed-fu'
gem 'therubyracer'
gem 'tumblr_client'
gem 'turbolinks'
gem 'twitter-typeahead-rails'
gem 'uglifier'
gem 'unicorn'
gem 'virtus'
gem 'yaml_db'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'mailcatcher'
  gem 'quiet_assets'
  gem 'rubocop', require: false
  gem 'thin'
end

group :test do
  gem 'database_cleaner'
  gem 'minitest'
  gem 'mini_backtrace'
  gem 'minitest-reporters'
  gem 'simplecov', require: false
  gem 'vcr'
  gem 'webmock'
end
